server:
  port: 8080
  servlet:
    context-path: /file-system

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

lodsve:
  file-system:
    type: oss
    access-key-id: ENC(yA33pwgwjBXwB/rd+ax54+R1Xnwg8kWI2/1D5OomKA0=)
    access-key-secret: ENC(1Mh7K7qX0hT+qxQdtx1Navci0yv5nidU/21rC25vFD43exNygei08A==)
    bucket-name: ENC(AH40x5SoAx4HgYSPEjIRg/vxGozC9nNGWRnqeLcvWs0=)
    oss:
      endpoint: oss-cn-shanghai.aliyuncs.com
